<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
<title>src/klotter/render/uniform_buffer.test.cc</title>
</head>
<body>
<h1>src/klotter/render/uniform_buffer.test.cc</h1>
<span id='bugprone-chained-comparison'>&nbsp;</span>
<hr>
<h3>warning: chained comparison &#39;v0 &lt;= v1 == v2&#39; may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions</h3>
<code>[bugprone-chained-comparison]</code>
<p><i>src/klotter/render/uniform_buffer.test.cc 31 : 2</i></p>
<pre>
   31 |         CHECK(value.offset == 0);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v0&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 31 : 2</i></p>
<pre>
   31 |         CHECK(value.offset == 0);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v1&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 31 : 8</i></p>
<pre>
   31 |         CHECK(value.offset == 0);
      |               ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<p>operand &#39;v2&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 31 : 24</i></p>
<pre>
   31 |         CHECK(value.offset == 0);
      |                               ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<hr>
<h3>warning: chained comparison &#39;v0 &lt;= v1 == v2&#39; may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions</h3>
<code>[bugprone-chained-comparison]</code>
<p><i>src/klotter/render/uniform_buffer.test.cc 32 : 2</i></p>
<pre>
   32 |         CHECK(vector.offset == 16);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v0&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 32 : 2</i></p>
<pre>
   32 |         CHECK(vector.offset == 16);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v1&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 32 : 8</i></p>
<pre>
   32 |         CHECK(vector.offset == 16);
      |               ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<p>operand &#39;v2&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 32 : 25</i></p>
<pre>
   32 |         CHECK(vector.offset == 16);
      |                                ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<hr>
<h3>warning: chained comparison &#39;v0 &lt;= v1 == v2&#39; may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions</h3>
<code>[bugprone-chained-comparison]</code>
<p><i>src/klotter/render/uniform_buffer.test.cc 33 : 2</i></p>
<pre>
   33 |         CHECK(matrix.offset == 32);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v0&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 33 : 2</i></p>
<pre>
   33 |         CHECK(matrix.offset == 32);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v1&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 33 : 8</i></p>
<pre>
   33 |         CHECK(matrix.offset == 32);
      |               ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<p>operand &#39;v2&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 33 : 25</i></p>
<pre>
   33 |         CHECK(matrix.offset == 32);
      |                                ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<hr>
<h3>warning: chained comparison &#39;v0 &lt;= v1 == v2&#39; may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions</h3>
<code>[bugprone-chained-comparison]</code>
<p><i>src/klotter/render/uniform_buffer.test.cc 34 : 2</i></p>
<pre>
   34 |         CHECK(values.offset == 96);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v0&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 34 : 2</i></p>
<pre>
   34 |         CHECK(values.offset == 96);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v1&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 34 : 8</i></p>
<pre>
   34 |         CHECK(values.offset == 96);
      |               ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<p>operand &#39;v2&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 34 : 25</i></p>
<pre>
   34 |         CHECK(values.offset == 96);
      |                                ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<hr>
<h3>warning: chained comparison &#39;v0 &lt;= v1 == v2&#39; may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions</h3>
<code>[bugprone-chained-comparison]</code>
<p><i>src/klotter/render/uniform_buffer.test.cc 35 : 2</i></p>
<pre>
   35 |         CHECK(boolean.offset == 144);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v0&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 35 : 2</i></p>
<pre>
   35 |         CHECK(boolean.offset == 144);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v1&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 35 : 8</i></p>
<pre>
   35 |         CHECK(boolean.offset == 144);
      |               ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<p>operand &#39;v2&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 35 : 26</i></p>
<pre>
   35 |         CHECK(boolean.offset == 144);
      |                                 ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<hr>
<h3>warning: chained comparison &#39;v0 &lt;= v1 == v2&#39; may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions</h3>
<code>[bugprone-chained-comparison]</code>
<p><i>src/klotter/render/uniform_buffer.test.cc 36 : 2</i></p>
<pre>
   36 |         CHECK(integer.offset == 148);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v0&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 36 : 2</i></p>
<pre>
   36 |         CHECK(integer.offset == 148);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v1&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 36 : 8</i></p>
<pre>
   36 |         CHECK(integer.offset == 148);
      |               ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<p>operand &#39;v2&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 36 : 26</i></p>
<pre>
   36 |         CHECK(integer.offset == 148);
      |                                 ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<hr>
<h3>warning: chained comparison &#39;v0 &lt;= v1 == v2&#39; may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions</h3>
<code>[bugprone-chained-comparison]</code>
<p><i>src/klotter/render/uniform_buffer.test.cc 37 : 2</i></p>
<pre>
   37 |         CHECK(setup.size == 152);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v0&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 37 : 2</i></p>
<pre>
   37 |         CHECK(setup.size == 152);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v1&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 37 : 8</i></p>
<pre>
   37 |         CHECK(setup.size == 152);
      |               ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<p>operand &#39;v2&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 37 : 22</i></p>
<pre>
   37 |         CHECK(setup.size == 152);
      |                             ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<hr>
<h3>warning: chained comparison &#39;v0 &lt;= v1 == v2&#39; may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions</h3>
<code>[bugprone-chained-comparison]</code>
<p><i>src/klotter/render/uniform_buffer.test.cc 53 : 2</i></p>
<pre>
   53 |         CHECK(projection.offset == 0);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v0&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 53 : 2</i></p>
<pre>
   53 |         CHECK(projection.offset == 0);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v1&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 53 : 8</i></p>
<pre>
   53 |         CHECK(projection.offset == 0);
      |               ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<p>operand &#39;v2&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 53 : 29</i></p>
<pre>
   53 |         CHECK(projection.offset == 0);
      |                                    ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<hr>
<h3>warning: chained comparison &#39;v0 &lt;= v1 == v2&#39; may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions</h3>
<code>[bugprone-chained-comparison]</code>
<p><i>src/klotter/render/uniform_buffer.test.cc 54 : 2</i></p>
<pre>
   54 |         CHECK(view.offset == 64);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v0&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 54 : 2</i></p>
<pre>
   54 |         CHECK(view.offset == 64);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v1&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 54 : 8</i></p>
<pre>
   54 |         CHECK(view.offset == 64);
      |               ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<p>operand &#39;v2&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 54 : 23</i></p>
<pre>
   54 |         CHECK(view.offset == 64);
      |                              ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<hr>
<h3>warning: chained comparison &#39;v0 &lt;= v1 == v2&#39; may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions</h3>
<code>[bugprone-chained-comparison]</code>
<p><i>src/klotter/render/uniform_buffer.test.cc 55 : 2</i></p>
<pre>
   55 |         CHECK(setup.size == 128);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v0&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 55 : 2</i></p>
<pre>
   55 |         CHECK(setup.size == 128);
      |         ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 22</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 47</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
</pre>
<p>operand &#39;v1&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 55 : 8</i></p>
<pre>
   55 |         CHECK(setup.size == 128);
      |               ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<p>operand &#39;v2&#39; is here</p>
<p><i>src/klotter/render/uniform_buffer.test.cc 55 : 22</i></p>
<pre>
   55 |         CHECK(setup.size == 128);
      |                             ^
</pre>
<p>expanded from macro &#39;CHECK&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 17677 : 97</i></p>
<pre>
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( &quot;CHECK&quot;, Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
</pre>
<p>expanded from macro &#39;INTERNAL_CATCH_TEST&#39;</p>
<p><i>external/catchy/external/catch/catch.hpp 2710 : 70</i></p>
<pre>
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() &lt;= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
</pre>
<!--
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:31:2: warning: chained comparison 'v0 <= v1 == v2' may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions [bugprone-chained-comparison]
   31 |         CHECK(value.offset == 0);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:31:2: note: operand 'v0' is here
   31 |         CHECK(value.offset == 0);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:31:8: note: operand 'v1' is here
   31 |         CHECK(value.offset == 0);
      |               ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:31:24: note: operand 'v2' is here
   31 |         CHECK(value.offset == 0);
      |                               ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:32:2: warning: chained comparison 'v0 <= v1 == v2' may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions [bugprone-chained-comparison]
   32 |         CHECK(vector.offset == 16);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:32:2: note: operand 'v0' is here
   32 |         CHECK(vector.offset == 16);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:32:8: note: operand 'v1' is here
   32 |         CHECK(vector.offset == 16);
      |               ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:32:25: note: operand 'v2' is here
   32 |         CHECK(vector.offset == 16);
      |                                ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:33:2: warning: chained comparison 'v0 <= v1 == v2' may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions [bugprone-chained-comparison]
   33 |         CHECK(matrix.offset == 32);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:33:2: note: operand 'v0' is here
   33 |         CHECK(matrix.offset == 32);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:33:8: note: operand 'v1' is here
   33 |         CHECK(matrix.offset == 32);
      |               ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:33:25: note: operand 'v2' is here
   33 |         CHECK(matrix.offset == 32);
      |                                ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:34:2: warning: chained comparison 'v0 <= v1 == v2' may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions [bugprone-chained-comparison]
   34 |         CHECK(values.offset == 96);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:34:2: note: operand 'v0' is here
   34 |         CHECK(values.offset == 96);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:34:8: note: operand 'v1' is here
   34 |         CHECK(values.offset == 96);
      |               ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:34:25: note: operand 'v2' is here
   34 |         CHECK(values.offset == 96);
      |                                ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:35:2: warning: chained comparison 'v0 <= v1 == v2' may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions [bugprone-chained-comparison]
   35 |         CHECK(boolean.offset == 144);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:35:2: note: operand 'v0' is here
   35 |         CHECK(boolean.offset == 144);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:35:8: note: operand 'v1' is here
   35 |         CHECK(boolean.offset == 144);
      |               ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:35:26: note: operand 'v2' is here
   35 |         CHECK(boolean.offset == 144);
      |                                 ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:36:2: warning: chained comparison 'v0 <= v1 == v2' may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions [bugprone-chained-comparison]
   36 |         CHECK(integer.offset == 148);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:36:2: note: operand 'v0' is here
   36 |         CHECK(integer.offset == 148);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:36:8: note: operand 'v1' is here
   36 |         CHECK(integer.offset == 148);
      |               ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:36:26: note: operand 'v2' is here
   36 |         CHECK(integer.offset == 148);
      |                                 ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:37:2: warning: chained comparison 'v0 <= v1 == v2' may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions [bugprone-chained-comparison]
   37 |         CHECK(setup.size == 152);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:37:2: note: operand 'v0' is here
   37 |         CHECK(setup.size == 152);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:37:8: note: operand 'v1' is here
   37 |         CHECK(setup.size == 152);
      |               ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:37:22: note: operand 'v2' is here
   37 |         CHECK(setup.size == 152);
      |                             ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:53:2: warning: chained comparison 'v0 <= v1 == v2' may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions [bugprone-chained-comparison]
   53 |         CHECK(projection.offset == 0);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:53:2: note: operand 'v0' is here
   53 |         CHECK(projection.offset == 0);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:53:8: note: operand 'v1' is here
   53 |         CHECK(projection.offset == 0);
      |               ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:53:29: note: operand 'v2' is here
   53 |         CHECK(projection.offset == 0);
      |                                    ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:54:2: warning: chained comparison 'v0 <= v1 == v2' may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions [bugprone-chained-comparison]
   54 |         CHECK(view.offset == 64);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:54:2: note: operand 'v0' is here
   54 |         CHECK(view.offset == 64);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:54:8: note: operand 'v1' is here
   54 |         CHECK(view.offset == 64);
      |               ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:54:23: note: operand 'v2' is here
   54 |         CHECK(view.offset == 64);
      |                              ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:55:2: warning: chained comparison 'v0 <= v1 == v2' may generate unintended results, use parentheses to specify order of evaluation or a logical operator to separate comparison expressions [bugprone-chained-comparison]
   55 |         CHECK(setup.size == 128);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:55:2: note: operand 'v0' is here
   55 |         CHECK(setup.size == 128);
      |         ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:22: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:47: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                               ^~~~~~~~~~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:55:8: note: operand 'v1' is here
   55 |         CHECK(setup.size == 128);
      |               ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
/home/runner/work/klotter/klotter/src/klotter/render/uniform_buffer.test.cc:55:22: note: operand 'v2' is here
   55 |         CHECK(setup.size == 128);
      |                             ^
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:17677:97: note: expanded from macro 'CHECK'
 17677 | #define CHECK( ... ) INTERNAL_CATCH_TEST( "CHECK", Catch::ResultDisposition::ContinueOnFailure, __VA_ARGS__ )
       |                                                                                                 ^~~~~~~~~~~
/home/runner/work/klotter/klotter/external/catchy/external/catch/catch.hpp:2710:70: note: expanded from macro 'INTERNAL_CATCH_TEST'
 2710 |             catchAssertionHandler.handleExpr( Catch::Decomposer() <= __VA_ARGS__ ); \
      |                                                                      ^~~~~~~~~~~
-->
</body>
</html>
